### ISSUE TITLE
'undefined' body sent in Microsoft Edge + solution

### ISSUE THREAD

**Issue by dhritzkiv** [Raynos/xhr#100]
I've recently encountered an error with Microsoft Edge where when submitting a DELETE request, the data `undefined` is being sent as the body, which my server rejects as its attempting to read it as `application/json`. For some reason, all other browsers (including IE) send the request fine, without a body.

This can be explained by the following lines:

```js
//L 121
body = options.body || options.data; //body === undefined

//L 182
xhr.send(body); //in Edge, XMLHttpRequest sends `undefined`; no good
```

I was wondering if something like this may work, at L121, as null is okay to pass into `send`, to explicitly denote that there is no body:

```js
//L 121
body = options.body || options.data || null; //body === null;
```

Any thoughts on this suggestion, or what else may be happening, or what I can do as a developer?

**Comment by naugtur** [comment]
Thanks for reporting.
It's going go be hard to wriye a test for this but we need to see what are the other browsers doing with null.

As a temporary workaround you can pass `data:null` in options and we'll add your suggested fix if it works with orher browsers

**Comment by dhritzkiv** [comment]
It appears there's long been precedent for `null` as the argument in `xhr.send`.

> The null parameter indicates that no body content is needed for the GET request.

from [MDN – Synchronous and asynchronous requests](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests)

In the meantime, I'll try the workaround, and will report if it addresses the issue.

**Comment by naugtur** [comment]
Done. Thanks for reporting.
