### ISSUE TITLE
Bad/out-of-order release: v2.1.0

### ISSUE THREAD

**Issue by dhritzkiv** [Raynos/xhr#102]
Seems that there was a release `v2.1.0` at some point, but the latest is reported as `v2.0.5` (this is true on npm and Github). Sometimes my npm acts a little screwy as a result. It's not a major issue, and will probably be naturally resolved once there's a version > `v2.1.0`. Could be worth running `npm unpublish xhr@v2.1.0`, however.

**Comment by naugtur** [comment]
Looks like a bad merge. I'll make sure everything's in place and release a 2.1.1 if needed. Seems like 2.0.5 was supposed to be that.

**Comment by naugtur** [comment]
Found it. 
Thanks for noticing. 
Deprecated v2.1.0
Merged it up and released the new convenience methods, which I was going to do anyway. 
Now latest is 2.2.0

**Comment by dhritzkiv** [comment]
Great!
