### ISSUE TITLE
Modifying URL/URI in beforeSend?

### ISSUE THREAD

**Issue by pixshatterer** [Raynos/xhr#103]
Seems like modifying url on beforeSend is not possible due to xhr connection already opened with the one already set... is this restriction enforced by design?

**Comment by naugtur** [comment]
The fact that beforeSend is invoked at the last moment before sending the request is by design.
So the answer is yes.

**Comment by pixshatterer** [comment]
Yup I already saw that - now, if beforeSend isn't able to change URL before sending the request due to being already "locked" when the request is opened. That's why I asked if this was done by design - url not being able to be changed on beforeSend - of this was a bug.  So, if this is blocked by design, there is a way to alter the url before request is send?

**Comment by naugtur** [comment]
URL is the main piece of input you pass to `xhr`. Why not wait with calling `xhr()` till you know what the URL should be? 
If you have a specific case you can post it to stackoverflow and add a link here. (githib is not designed for that, but I can help you if you're not in a rush)
