### ISSUE TITLE
Allow Cross Origin?

### ISSUE THREAD

**Issue by JeremyCarlsten** [Raynos/xhr#109]
First off. I'm probably using it incorrectly somehow. I'm attempting to use the wrapper in a react app calling a simple express server hosted on heroku to mock some data. 
```
var xhr = require('xhr');
...
 componentDidMount: function() {
        var self = this;
        xhr.get('https://test-app-data.herokuapp.com/testData',
            function(err, response){
                self.setState({appDataList :response.body});
                console.log(response.body);
          });
    },
...

```

I keep getting the ole No 'Access-Control-Allow-Origin' header error. Is this a bug, or am I completely 
mis-using something? 

Thanks in advance, 
Jeremy

**Comment by naugtur** [comment]
You can't just make a crossdomain request to any domain. The server has to agree. That's what 'Access-Control-Allow-Origin' header is for. If you control the server, you need to add this to your express: https://www.npmjs.com/package/cors
