### ISSUE TITLE
204 (no content) responses return an XMLDocument in Firefox

### ISSUE THREAD

**Issue by TehShrike** [Raynos/xhr#111]
When the server returns a 204, firefox sets `responseXML` to an XML document - a truthy object.

This is apparently a [long-standing Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=521301).

Since `xhr` is abstracting away `response`/`responseText`/`responseXML`, this means that `xhr` returns something other than null/undefined/empty string in Firefox when the server returns a 204.

https://github.com/Raynos/xhr/blob/master/index.js#L74

Would you be open to a pull request to fix this?  How would you prefer that this was fixed?  A check for a 204 status code that always returns null/undefined?  Or maybe return `responseText` as long as it's a string, so that an empty string is returned?

I've opened a pull request with a failing test: #112

**Comment by TehShrike** [comment]
It looks like #106 is actually an attempt at a solution to this issue.

**Comment by reqshark** [comment]
> you could cache a regex for navigator.userAgent string. maybe some part of the string could range limit a few versions beginning around when 204 XML buggy firefox appeared on bugzilla

> run that regex.test() operation after detecting a 204 response

oops, i put my idea in your PR #112.. but u asked for that commentary here on the issue... ^ there ya go

**Comment by TehShrike** [comment]
lol, and I replied there too, because I am also bad at reading where I am

**Comment by reqshark** [comment]
yea close the issue because the info here got ref linked to the PR and that's a better spot to flush it out versus tab switching the same thing again on the same issue

**Comment by reqshark** [comment]
sorry dont close

keep this issue open until it gets fixed. 

the first things mentioned here are good descriptions of the firefox scenario, explaining how that set of multiple browser API response values get wrapped into one erroneous particular 204 case. 

that's helpful for context ^ 

now to continue our discussion at #112

**Comment by TehShrike** [comment]
I opened two pull requests with potential fixes: 
- As suggested by @naugtur in https://github.com/Raynos/xhr/pull/112#issuecomment-223742778, pull request #117 only returns the XML document if the `responseType` is `"document"`.
- Another option would be to not use the XML document if the status code is 204 and there was an error parsing the XML document: #118

**Comment by naugtur** [comment]
I'm still in favor of the first option. I'll have enough time to give both PRs the attention they deserve on Friday.

**Comment by TehShrike** [comment]
It would technically be a breaking change, but I agree that's the correct change.

**Comment by TehShrike** [comment]
I've suggested another possible flavor of solution in #121.

It seems like it would be better to merge and deploy any of the open pull request than to leave this open bug.
