### ISSUE TITLE
xhr.open is not a function

### ISSUE THREAD

**Issue by nichoth** [Raynos/xhr#116]
```
xhr.open(method, uri, !sync, options.username, options.password)
        ^

TypeError: xhr.open is not a function
    at _createXHR (/Users/nick/invintus/api-adapter/node_modules/xhr/index.js:174:9)
    at Function.createXHR.(anonymous function) [as post] (/Users/nick/invintus/api-adapter/node_modules/xhr/index.js:16:16)
    at fetch (/Users/nick/invintus/api-adapter/index.js:21:9)
    at Object.<anonymous> (/Users/nick/invintus/api-adapter/example/index.js:7:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
api-adapter(master) nick$ vim node_modules/xhr/index.js
```

**Comment by orrybaram** [comment]
@nichoth what was the solution for this? im getting the same issue

**Comment by TehShrike** [comment]
This module doesn't have an `open` method: https://github.com/Raynos/xhr#other-signatures

The docs are a bit confusing because they sometimes use `xhr` to refer to an XMLHttpRequest, instead of the library.  I'll open a PR to fix that.

**Comment by orrybaram** [comment]
I think it was cause I was trying to use it server side accidentally.

**Comment by TehShrike** [comment]
I think you're right.  And looking at the stack trace more closely, I'll bet that's what nichoth was running into too.

**Comment by nichoth** [comment]
Yes, I was using it in Node, but it's browser only. See the `nets` module for something that works in both.

**Comment by naugtur** [comment]
I didn't expect that to happen... Why did you think it'll work in node? Maybe I can change some wording on the initial sentence declaring it's for browserify and alike...

**Comment by nichoth** [comment]
No reason really, just spacing out and forgetting where my code is running :)

**Comment by dfcreative** [comment]
@naugtur it is actually in the readme,
> API is a subset of request so that the same code can be used in the browser and Node.js.

I understood that as it is going to work in node

**Comment by TehShrike** [comment]
Ah, I can see how that would cause confusion.  I've suggested an edit in #132 that should hopefully make that clearer.

**Comment by chrisl777** [comment]
I was writing unit tests in Node.js, and was having the problem above. In case it's not clear on this thread, use require('request') instead of require('xhr'), then modify your project settings to substitute in xhr in the browser. The docs have been updated to reflect that.
