### ISSUE TITLE
Callback executing twice?

### ISSUE THREAD

**Issue by timwis** [Raynos/xhr#127]
Originally reported in yoshuawuyts/choo#193:

> I have an effect that calls multiple effects using `run-waterfall`. The "sub" effects use the `choo/http` module to make an http request. When the requests encounter an error, they `return done('Bad request')`. This error message bubbles up to the parent effect, which calls `done(err)` itself, bubbling it up to the application event handler, which logs an uncaught error.

> The problem is the uncaught error is being logged twice. [Here's a test case](http://requirebin.com/?gist=5a5b69a86a1a5fa41d16011886138b6a) to demonstrate. If you switch out the http call with the `setTimeout` call, it only logs once. Also if you comment out the `done(err)` in the parent effect, it only logs once.

> Am I crazy or is this unexpected behaviour?

@yoshuawuyts investigated and believes `xhr` is calling the callback twice. Would it be helpful to alter the test case to demonstrate it without choo? Or is this enough to diagnose?

Thanks for your help

**Comment by naugtur** [comment]
I'll try to diagnose based on what you already have and lat you know in an hour.

**Comment by yoshuawuyts** [comment]
Quick note: this only happens when used in `choo`, but not without it. There's no obvious interaction between the two libs tho so I've got no idea why `xhr` is calling back twice

**Comment by naugtur** [comment]
I couldn't reproduce with just `xhr` either. In debugger now. 
Sourcemaps in the testcase would help... ;)

**Comment by naugtur** [comment]
Observation:

first call goes through this in callstack:
```
callback(...)
callback=noop
```
second call does
```
callback(...)
```
and is not invoking a noop function.

Possible explanations:
- callback is somehow calling xhr again or changing state of the XMLHttpRequest object being handled before it returns
- I'm going insane

**Comment by naugtur** [comment]
Ok, found it.

Root cause is: if you throw inside xhr callback, the code that guarantees it runs only once does not execute.

I'll have a fix for that in minutes

**Comment by yoshuawuyts** [comment]
Yay, nice! :grin:
