### ISSUE TITLE
`responseType` – ignore 204 No Content?

### ISSUE THREAD

**Issue by jmeas** [Raynos/xhr#128]
My API returns JSON objects always, except in certain situations when a `204 No Content` is returned. This is used, for instance, for successful deletes. (for further reading, check out [the JSON API](http://jsonapi.org/format/#crud-deleting) spec)

Setting `responseType: 'json'` blows up when this happens, because an empty response isn't json. The immediate reaction might be, well, don't specify the response type. I'd like to, however, because errors and all other unsuccessful deletes are returned in a JSON format.

Do folks think that it makes sense for `responseType` to skip trying to parse the (nonexistent) body if `204` is returned?

**Comment by jmeas** [comment]
Oops – should have searched better. Just found this PR: https://github.com/Raynos/xhr/pull/106

**Comment by jmeas** [comment]
Gonna reopen 'cause the JSON issue still seems to be a problem in `2.2.2`.

**Comment by naugtur** [comment]
`responseType` is a feature of XMLHttpRequest object [see MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) and it's implemented by the browser as standard describes. It requires a JSON response no matter what and there's nothing `xhr` can do about it. Also, I'm not sure what the browser support is.

What you actually want is the `json` option for `xhr` (see README.md [here](https://github.com/Raynos/xhr#optionsjson) and [here](https://github.com/Raynos/xhr#faq))
It will not throw an error if parsing JSON fails.

**Comment by jmeas** [comment]
Thanks, @naugtur ! I didn't think to use it because the docs only use the GET request example. Would you be open for a PR to make it a teeny bit more explicit how `json` can be used, and how it differs from `responseType`?

**Comment by naugtur** [comment]
Sure!

It's demonstrated for GET because it wasn't obvious even for https://github.com/request/request users
I'm looking forward to a cleaner explanation. All I can ask is that you make sure it's short and not stealing attention from everything else in the README.md - other than that, there's nothing stopping what you write from getting merged.

**Comment by jmeas** [comment]
> Sure!

Awesome. I'll whip up a PR sometime in the next few days.

> All I can ask is that you make sure it's short and not stealing attention from everything else in the README.md - other than that, there's nothing stopping what you write from getting merged.

Noted. I'll keep it succinct. :v:
