### ISSUE TITLE
crash in Firefox when sync == true

### ISSUE THREAD

**Issue by brunal** [Raynos/xhr#65]
when `sync == true`  `xhr` will crash with the following error:
```
InvalidAccessError: A parameter or an operation is not supported by the underlying object
```
On the line
```
xhr.withCredentials = !!options.withCredentials
```
On [the related MDN page](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) it is said that

    Note: Starting with Gecko 11.0 (Firefox 11.0 / Thunderbird 11.0 / SeaMonkey 2.8), Gecko no
    longer lets you use the withCredentials attribute when performing synchronous requests.
    Attempting to do so throws an NS_ERROR_DOM_INVALID_ACCESS_ERR exception.

**Comment by naugtur** [comment]
I fixed code style and added a testcase. 
@Raynos I didn't tag&publish it yet, so that you can still Veto.
