### ISSUE TITLE
Why 2.0?

### ISSUE THREAD

**Issue by zeke** [Raynos/xhr#67]
What change to xhr caused the major version bump?

**Comment by naugtur** [comment]
Two main things:
1. xhr was supposed to be a replacement for *request* and 1.x would return HTTP responses of 400+ as errors, while *request* did not. We changed that and now the callback is only called with first argument not `null` when there is an error making the request
2. xhr used to extend the XMLHttpRequest object and return it as a second argument, but for old IEs it couldn't be done, so turning on IE support changed the response format, which was hard to maintain for developers using it. We changed the format of the response object to be much simpler and IE compatible.

As a result it's not going to 'just work' if you replace xhr 1.x with 2.0 in your dependencies.

**Comment by landau** [comment]
:+1: Changelog please! :)

**Comment by zeke** [comment]
Yeah a changelog would be nice.

xhr@2 landed in nets@3: https://www.npmjs.com/package/nets
