### ISSUE TITLE
support for `form` option?

### ISSUE THREAD

**Issue by FredKSchott** [Raynos/xhr#75]
The [request](https://github.com/request/request) library has a helpful `form` option, which is the equivalent of doing:
```js
request({
    form: body
})
// is equivalent to...
request({
    body: querystring.stringify(body).toString('utf8'),
    headers: {"Content-Type": "application/x-www-form-urlencoded"}
})
```

The option handles the body stringification & header-setting for me, which I find much easier to work with. Is there any interest to add a similar option to xhr? It would make moving from `request` to `nets` much easier for myself and a lot of others.

Happy to submit a PR if so.

**Comment by Raynos** [comment]
@FredKSchott I'd rather not add the weight of a querystring library to this package.

The `form` feature is uncommon and is best done somewhere else in a convenience library.

The point of this library, `xhr` is to have a node-style interface to `XMLHttpRequest`. That being said; maybe it's fair to remove json convenience from `xhr` as well; although that would make it less useful..

**Comment by FredKSchott** [comment]
That makes sense, thanks for the quick response!
