### ISSUE TITLE
Easy access to cookies?

### ISSUE THREAD

**Issue by EvanCarroll** [Raynos/xhr#76]
Is there an easy helper to get access to the cookie information, or do we have to parse the header ourselves? If not, would you accept a patch that parsed the cookie information and accepted a key, returning the cookie's value?

**Comment by naugtur** [comment]
xhr is supposed to be lightweight. 
We don't include querystring builder nor parser, because there's `qs` that does it.
Same thing should apply to this case imho

Pseudocode:
```javascript
var cookieparser = require('something...');
cookies = cookieparser(headersFromXhr["set-cookie"])
```

I'll check if there isn't one, and if not, we can build a parser like that. Just not inside the main xhr file.
