### ISSUE TITLE
We lost IE8/9 support

### ISSUE THREAD

**Issue by naugtur** [Raynos/xhr#77]
I checked on virtual machines at work, and we lost support for old IEs
It seems that the only problem for now is that parse-headers is using `.indexOf`
Good news: noone reported that ;)

1. We need to re-run tests in IEs more often. Who can help? Who has experience with browserstack free for opensource option?
2. Change `parse-headers` or replace with something else?
3. Integration tests are not IE compatible, I'll fix them  by the end of the week (my bad)

**Comment by Raynos** [comment]
Hmm.

One of the reasons why there are no reports is that most people are still pinned to 1.x

We should fix the issue and look into saucelabs using Zuul.

Mercury and virtual Dom run ie tests there

**Comment by naugtur** [comment]
I'm spinning up a vm from MS to get back to debugging this thing.
parse-headers was in our dependencies in 1.x too as far as I remember. But I'm not sure if the problem with `.indexOf` wasn't a result of an incorrect response from the server or something.

I'll come back when I know something ;)

**Comment by naugtur** [comment]
Probably a false alarm.
After a lot of pain I can say that `xhr` seems to be working in IE8 just as expected (some cross-domain features not working for IE reasons)
It's our infrastructure that doesn't work in IEs anymore.

1. run-browser adds a console replacement that uses some methods that aren't there
2. tests were missing `useXDR` and tried to test features that are impossible in IE8

We won't func-test basic features in IEs without a localhost server. I'll see if it's possible to use paths that can be accessed with run-browser.

**Comment by naugtur** [comment]
Quite a delay, but I updated dev-dependencies and fixed tests https://github.com/Raynos/xhr/commit/adf63ad3c4415f9aa5d31f421b1e367593bdcffd

Opening a new issue for Zuul #81
