### ISSUE TITLE
Where did the 2.0.2 hide?

### ISSUE THREAD

**Issue by naugtur** [Raynos/xhr#87]
I published a new version recently, but I couldn't publish 2.0.2 because it was already taken. There is no tag for 2.0.2. I can't find it, so I published 2.0.3 and all's well. But I feel like we should tag the 2.0.2 on the right commit or unpublish 2.0.2
I couldn't find the commit that was published as 2.0.2. That's the magic of DVCS ;)

**Comment by eins78** [comment]
Maybe I can help (if I understood the question correctly):
7d3d5b5

In case I am not correct, some more detail on how I tried to find out, maybe it helps you looking 
("magic of DVCS" reminded me of something I read on a mailing list a while ago):

This [SO answer](http://stackoverflow.com/a/223890) has a small shell script that finds git blobs that contain the exact version of a file. 
I did `npm i xhr@2.0.2`, and ran the script against the `index.html`. Results: f7a4a45, 7d3d5b5 and eccc209.

**Comment by naugtur** [comment]
7d3d5b5 is where I bumped the version number thinking it's free. After that I published to npm and got a reject saying the version exists.
To me it looks like 2.0.2 was tagged at some point before that and released without pushing the tag. Seems like all changes except the tag and version bump are in the repo.

Anyway, thanks for you for help and great SO link! I'll certainly play with it
