### ISSUE TITLE
isomorphism

### ISSUE THREAD

**Issue by kumavis** [Raynos/xhr#99]
would you add [node-XMLHttpRequest](https://github.com/driverdan/node-XMLHttpRequest) as a dependency if we marked it as 'false' in the browser field?

would make xhr nicely isomorphic w/o any overhead in the browser bundle

**Comment by naugtur** [comment]
I'm not sure about that... 
`xhr` is supposed to be a replacement for `request` in browserify etc. and making it isomorphic seems to defeat that purpose. 

@Raynos what do you think about this idea?

**Comment by Raynos** [comment]
:-1: browser and node http are different beasts.

Never should they merge. Write your own isomorphic library that wraps xhr and request

**Comment by kumavis** [comment]
> making it isomorphic seems to defeat that purpose.
request browserifies to 0.8MB, this comes through small, which is really nice. adding the isomorphism wont change that.
> Never should they merge. 
disagree

**Comment by reqshark** [comment]
> browser and node http are different beasts

yea, unhandled errors from the network don't necessarily stop an app's runtime/callstack in the browser

**Comment by kumavis** [comment]
well, im assuming we are sticking with XHR's behavior, and so the onus to behave in node as it does in the browser is a concern upstream in `node-XMLHttpRequest`

**Comment by naugtur** [comment]
@kumavis
it seems to me you didn't get what xhr is for. Xhr is the replacement for request if you want to browserify your code. Most of the features will work the same.
Check how xhr is used in ampersand-sync (start in package.json)

**Comment by davidgilbertson** [comment]
I actually just assumed that this would work in node or the browser. Fine that it doesn't, but a note in the readme that says this client-side only might be helpful.

**Comment by naugtur** [comment]
How about the first line of readme updated in 2014 by Max Ogden? ;)
https://github.com/Raynos/xhr/commit/b56b23ac30e1f265ba3c98bf767a36e3c15661f6

But to make sure this confusion never happens again, I'm going to explicitly state that xhr is designed as a replacement for `request` from nodejs.

**Comment by davidgilbertson** [comment]
@naugtur Sweet. Yep I read that as ' this is designed so it works with browerify'. Like `lodash` or `immutable` or `promise` all 'work' with browserify.

Maybe I'm just a little simple :).

**Comment by naugtur** [comment]
yup. I've used it in one project recently
